import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defaultSyncSettings } from "./presets.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** App root (repo root in dev; resources/hub or asar.unpacked in packaged builds). */
export const ROOT_DIR = process.env.ARRS_HUB_ROOT
  ? path.resolve(process.env.ARRS_HUB_ROOT)
  : path.resolve(__dirname, "..");

/**
 * Writable settings/recyclarr dir.
 * Packaged desktop sets ARRS_HUB_DATA_DIR to %APPDATA%/Arrs Hub/data.
 */
export const DATA_DIR = process.env.ARRS_HUB_DATA_DIR
  ? path.resolve(process.env.ARRS_HUB_DATA_DIR)
  : path.join(ROOT_DIR, "data");

export const RECYCLARR_DIR = path.join(DATA_DIR, "recyclarr");
export const SETTINGS_PATH = path.join(DATA_DIR, "sync-settings.json");
export const CONFIG_PATH = path.join(RECYCLARR_DIR, "recyclarr.yml");
export const EXE_PATH = path.join(RECYCLARR_DIR, "recyclarr.exe");

export function ensureDataDirs() {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.mkdirSync(RECYCLARR_DIR, { recursive: true });
}

export function loadSyncSettings() {
  ensureDataDirs();
  if (!fs.existsSync(SETTINGS_PATH)) {
    const defaults = defaultSyncSettings();
    saveSyncSettings(defaults);
    return defaults;
  }
  const raw = JSON.parse(fs.readFileSync(SETTINGS_PATH, "utf8"));
  return {
    ...defaultSyncSettings(),
    ...raw,
    sonarr: { ...defaultSyncSettings().sonarr, ...(raw.sonarr ?? {}) },
    radarr: { ...defaultSyncSettings().radarr, ...(raw.radarr ?? {}) },
  };
}

export function saveSyncSettings(settings) {
  ensureDataDirs();
  fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2), "utf8");
}

export function yamlQuote(value) {
  return JSON.stringify(String(value));
}

/**
 * Build Recyclarr v8 YAML (quality_definition + trash_id profiles).
 * Multiple presets for the same arr are merged into one instance.
 */
export function buildRecyclarrYaml(settings, presets) {
  /** @type {Record<string, { base_url: string, api_key: string, quality_definition: string, profiles: { trashId: string, profileName: string }[] }>} */
  const sonarr = {};
  /** @type {Record<string, { base_url: string, api_key: string, quality_definition: string, profiles: { trashId: string, profileName: string }[] }>} */
  const radarr = {};

  for (const preset of presets) {
    const serviceSettings = settings[preset.service];
    if (!serviceSettings?.enabled) continue;
    if (!serviceSettings.apiKey?.trim()) continue;

    const bucket = preset.service === "sonarr" ? sonarr : radarr;
    // Instance names must be unique across Sonarr AND Radarr or Recyclarr
    // silently skips sync ("Duplicate instances").
    const key = preset.service;

    if (!bucket[key]) {
      bucket[key] = {
        base_url: serviceSettings.baseUrl.replace(/\/$/, ""),
        api_key: serviceSettings.apiKey.trim(),
        quality_definition: preset.qualityDefinition,
        profiles: [],
      };
    }

    if (!bucket[key].profiles.some((p) => p.trashId === preset.trashId)) {
      bucket[key].profiles.push({
        trashId: preset.trashId,
        profileName: preset.profileName,
      });
    }
  }

  const lines = [
    "# Generated by Arrs Hub for Recyclarr v8+",
    "# Uses guide-backed trash_id profiles (include templates were removed in v8).",
    "",
  ];

  const writeService = (name, instances) => {
    const keys = Object.keys(instances);
    if (keys.length === 0) return;
    lines.push(`${name}:`);
    for (const key of keys) {
      const cfg = instances[key];
      lines.push(`  ${key}:`);
      lines.push(`    base_url: ${yamlQuote(cfg.base_url)}`);
      lines.push(`    api_key: ${yamlQuote(cfg.api_key)}`);
      lines.push(`    quality_definition:`);
      lines.push(`      type: ${cfg.quality_definition}`);
      lines.push(`    quality_profiles:`);
      for (const profile of cfg.profiles) {
        lines.push(`      - trash_id: ${profile.trashId}  # ${profile.profileName}`);
        lines.push(`        reset_unmatched_scores:`);
        lines.push(`          enabled: true`);
      }
      lines.push("");
    }
  };

  writeService("sonarr", sonarr);
  writeService("radarr", radarr);

  if (Object.keys(sonarr).length === 0 && Object.keys(radarr).length === 0) {
    throw new Error(
      "Nothing to sync. Enable Sonarr/Radarr, add API keys, and select at least one profile.",
    );
  }

  return lines.join("\n");
}
