import { SERVICE_ICONS } from "./assets/icons";
import type { ServiceDefinition } from "./types";

/** Remote LAN/WAN base used in Chrome bookmarks (plex → remote). */
const REMOTE_HOST = "http://67.84.101.14";

export const DEFAULT_SERVICES: ServiceDefinition[] = [
  {
    id: "sonarr",
    name: "Sonarr",
    description: "TV show management and automation",
    category: "media-management",
    defaultUrl: "http://localhost:8989",
    defaultRemoteUrl: `${REMOTE_HOST}:8989`,
    icon: SERVICE_ICONS.sonarr,
    color: "#35c5f4",
  },
  {
    id: "radarr",
    name: "Radarr",
    description: "Movie management and automation",
    category: "media-management",
    defaultUrl: "http://localhost:7878",
    defaultRemoteUrl: `${REMOTE_HOST}:7878`,
    icon: SERVICE_ICONS.radarr,
    color: "#ffc230",
  },
  {
    id: "lidarr",
    name: "Lidarr",
    description: "Music collection management",
    category: "media-management",
    defaultUrl: "http://localhost:8686",
    defaultRemoteUrl: `${REMOTE_HOST}:8686`,
    icon: SERVICE_ICONS.lidarr,
    color: "#35c5f4",
  },
  {
    id: "readarr",
    name: "Readarr",
    description: "Book and audiobook management",
    category: "media-management",
    defaultUrl: "http://localhost:8787",
    defaultRemoteUrl: `${REMOTE_HOST}:8787`,
    icon: SERVICE_ICONS.readarr,
    color: "#ffc230",
  },
  {
    id: "calibre",
    name: "Calibre",
    description: "Ebook library and content server",
    category: "media-management",
    defaultUrl: "http://localhost:8080",
    defaultRemoteUrl: `${REMOTE_HOST}:8080`,
    icon: SERVICE_ICONS.calibre,
    color: "#45b29d",
  },
  {
    id: "prowlarr",
    name: "Prowlarr",
    description: "Indexer manager for all *arr apps",
    category: "indexers",
    defaultUrl: "http://localhost:9696",
    defaultRemoteUrl: `${REMOTE_HOST}:9696`,
    icon: SERVICE_ICONS.prowlarr,
    color: "#e66000",
  },
  {
    id: "flaresolverr",
    name: "FlareSolverr",
    description: "Cloudflare / anti-bot proxy for indexers",
    category: "indexers",
    defaultUrl: "http://localhost:8191",
    defaultRemoteUrl: `${REMOTE_HOST}:8191`,
    icon: SERVICE_ICONS.flaresolverr,
    color: "#f97316",
  },
  {
    id: "ytarr",
    name: "Ytarr",
    description: "YouTube channel downloads (*arr-style)",
    category: "media-management",
    defaultUrl: "http://localhost:8199",
    defaultRemoteUrl: `${REMOTE_HOST}:8199`,
    icon: SERVICE_ICONS.ytarr,
    color: "#3fb950",
  },
  {
    id: "qbittorrent",
    name: "qBittorrent",
    description: "BitTorrent download client",
    category: "downloaders",
    defaultUrl: "http://localhost:8080",
    defaultRemoteUrl: `${REMOTE_HOST}:8079`,
    icon: SERVICE_ICONS.qbittorrent,
    color: "#2f67d2",
  },
  {
    id: "sabnzbd",
    name: "SABnzbd",
    description: "Usenet download client",
    category: "downloaders",
    defaultUrl: "http://localhost:8085",
    defaultRemoteUrl: `${REMOTE_HOST}:6789/sabnzbd/`,
    icon: SERVICE_ICONS.sabnzbd,
    color: "#ffc230",
  },
  {
    id: "ombi",
    name: "Ombi",
    description: "Media request portal for users",
    category: "requests",
    defaultUrl: "http://localhost:3579",
    defaultRemoteUrl: `${REMOTE_HOST}:5000/discover`,
    icon: SERVICE_ICONS.ombi,
    color: "#e5a00d",
  },
  {
    id: "overseerr",
    name: "Overseerr",
    description: "Modern request management for Plex",
    category: "requests",
    defaultUrl: "http://localhost:5055",
    icon: SERVICE_ICONS.overseerr,
    color: "#6366f1",
  },
  {
    id: "tautulli",
    name: "Tautulli",
    description: "Plex monitoring and statistics",
    category: "monitoring",
    defaultUrl: "http://localhost:8181",
    defaultRemoteUrl: `${REMOTE_HOST}:8181/home`,
    icon: SERVICE_ICONS.tautulli,
    color: "#e5a00d",
  },
  {
    id: "fileflows",
    name: "FileFlows",
    description: "Automated file processing workflows",
    category: "automation",
    defaultUrl: "http://localhost:19200",
    defaultRemoteUrl: `${REMOTE_HOST}:19200`,
    icon: SERVICE_ICONS.fileflows,
    color: "#10b981",
  },
  {
    id: "plex",
    name: "Plex",
    description: "Media server and streaming",
    category: "other",
    defaultUrl: "http://localhost:32400/web",
    defaultRemoteUrl: `${REMOTE_HOST}:32400/web`,
    icon: SERVICE_ICONS.plex,
    color: "#e5a00d",
  },
  {
    id: "trash-guides",
    name: "TRaSH Guides",
    description: "Recommended *arr quality profiles & formats",
    category: "other",
    defaultUrl: "https://trash-guides.info/",
    defaultRemoteUrl: "https://trash-guides.info/",
    icon: SERVICE_ICONS["trash-guides"],
    color: "#22c55e",
  },
  {
    id: "bazarr",
    name: "Bazarr",
    description: "Subtitle management for Sonarr & Radarr",
    category: "automation",
    defaultUrl: "http://localhost:6767",
    defaultRemoteUrl: `${REMOTE_HOST}:6767`,
    icon: SERVICE_ICONS.bazarr,
    color: "#e66000",
  },
  {
    id: "whisparr",
    name: "Whisparr",
    description: "Adult content management",
    category: "media-management",
    defaultUrl: "http://localhost:6969",
    icon: SERVICE_ICONS.whisparr,
    color: "#ec4899",
    defaultEnabled: false,
  },
];
